# Constants used across the Radar AI backend

# List of NIFTY 50 stocks
NIFTY_STOCKS = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "TITAN.NS",
    "SUNPHARMA.NS", "WIPRO.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "POWERGRID.NS"
]

# Thresholds for stock analysis
BREAKOUT_THRESHOLD = 0.98
VOLUME_SPIKE_MULTIPLIER = 1.5
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
LOOKBACK_PERIOD = "6mo"
TOP_OPPORTUNITIES = 5
MIN_SIGNALS_REQUIRED = 1
